### ISSUE TITLE
Add `module-to-cdn` as dependency

### ISSUE THREAD

**Issue by shytikov** [mastilver/dynamic-cdn-webpack-plugin#48] opened 2018-08-03 13:10 UTC
Hi,

I have tried to use `dynamic-cdn-webpack-plugin` in my `webpack.config.js` and I got following error message:

```
Error: Cannot find module 'module-to-cdn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (c:\Workspace\project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at getResolver (c:\Workspace\project\node_modules\dynamic-cdn-webpack-plugin\lib\get-resolver.js:12:12)
    at new DynamicCdnWebpackPlugin (c:\Workspace\project\node_modules\dynamic-cdn-webpack-plugin\lib\index.js:83:51)
    at Object.<anonymous> (c:\Workspace\project\front.core.config.js:73:5)
    at Module._compile (c:\Workspace\project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (c:\Workspace\project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (c:\Workspace\project\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (c:\Workspace\project\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at c:\Workspace\project\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (c:\Workspace\project\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (c:\Workspace\project\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (c:\Workspace\project\node_modules\yargs\yargs.js:563:18)
    at c:\Workspace\project\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (c:\Workspace\project\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

When I manually add `module-to-cdn` as a dependency to the project, everything starts working as it should. I believe the easiest fixes will be just move `module-to-cdn` from `peerDependencies` to just `dependencies`. By that package would be automatically delivered to a calling project.

**Comment by shytikov** [comment] 2018-08-03 13:14
I believe this is change that was done in `npm@3`. Not sure will you agree with proposed resolution or not... Maybe there are something more elegant...

But this warning:

```
npm WARN dynamic-cdn-webpack-plugin@4.0.0-rc.1 requires a peer of module-to-cdn@^3.1.1 but none is installed. You must install peer dependencies yourself.
```

Is just so easy to miss...

**Comment by mastilver** [comment] 2018-08-03 14:33
it should probably give you a nicer error, but I would like to keep it that way so anyone can use the resolver they want

**Comment by mastilver** [comment] 2018-08-03 14:34
Should be pretty straight forward to wrap that in a try..catch: https://github.com/mastilver/dynamic-cdn-webpack-plugin/blob/ec4ae4d12a2d37c4938be6e1deb026f853621854/src/get-resolver.js#L6

**Comment by aulisius** [comment] 2018-08-03 18:53
What would the catch do though? Log an error and exit execution?

**Comment by mastilver** [comment] 2018-08-26 14:09
Closing as it's an intended behavior

**Closed by mastilver** 2018-08-26 14:09 UTC
